# NumPy

- Numpy is short for Numerical Python. It is used for numerical computing.
- It is widely used for numerical computing in industries such as Data Science and AI.
- It is much faster than Python.
- It handles large scale numerical computing efficiently.

In [1]:
import numpy as np

In [25]:
# Create a NumPy array
arr1 = np.array([1, 2, 3, 4])
print(arr1)
print(type(arr1))
print("-"*15)

# Multiply each element in a NumPy array by 2
arr1 = arr1 * 2
print(arr1)
print("-"*15)

# Check the number of dimensions in an NumPy array
arr2 = np.array([[1, 2, 3], ['a','b','c']])
print(arr2)
print(arr2.ndim)
print("-"*15)

# Create a three-dimensional array
arr3 = np.array([
    [[1, 2, 3], ['a','b','c']],
    [[1, 2, 3], ['a','b',' ']],
    [[1, 2, 3], ['a','b',' ']],
    [[1, 2, 3], ['a','b',' ']]
])
print(arr3)
print(arr3.ndim)
print("-"*15)

# Check the shape of the array
print(arr3.shape) # (layers, rows, columns)
print("-"*15)

[1 2 3 4]
<class 'numpy.ndarray'>
---------------
[2 4 6 8]
---------------
[['1' '2' '3']
 ['a' 'b' 'c']]
2
---------------
[[['1' '2' '3']
  ['a' 'b' 'c']]

 [['1' '2' '3']
  ['a' 'b' ' ']]

 [['1' '2' '3']
  ['a' 'b' ' ']]

 [['1' '2' '3']
  ['a' 'b' ' ']]]
3
---------------
(4, 2, 3)


In [31]:
# Chain indexing
print(arr3[0][0][0])

# Multi-dimensional indexing
print(arr3[1, 1, 1])
print("-"*15)

# Row Slicing (array[start:end:step])
arr4 = np.array([[1,2,3,4], 
                 [5,6,7,8], 
                 [9,10,11,12], 
                 [13,14,15,16]])
print(arr4[1:3])
print("-"*15)
print(arr4[::2])

1
b
---------------
[[ 5  6  7  8]
 [ 9 10 11 12]]
---------------
[[ 1  2  3  4]
 [ 9 10 11 12]]


In [37]:
# Column Slicing (array[start:end:step])
arr4 = np.array([[1,2,3,4], 
                 [5,6,7,8], 
                 [9,10,11,12], 
                 [13,14,15,16]])

print(arr4[:, 2]) # arr4[row, column])
print("-"*15)
print(arr4[:2, -2:]) # First two rows and last two columns
print("-"*15)
print(arr4[-2:, ::-1]) # Last two rows and reverse the order for each column

[ 3  7 11 15]
---------------
[[3 4]
 [7 8]]
---------------
[[12 11 10  9]
 [16 15 14 13]]
