# NumPy

- Numpy is short for Numerical Python. It is used for numerical computing.
- It is widely used for numerical computing in industries such as Data Science and AI.
- It is much faster than Python.
- It handles large scale numerical computing efficiently.

In [3]:
import numpy as np

In [4]:
# Create a NumPy array
arr1 = np.array([1, 2, 3, 4])
print(arr1)
print(type(arr1))
print("-"*15)

# Multiply each element in a NumPy array by 2
arr1 = arr1 * 2
print(arr1)
print("-"*15)

# Check the number of dimensions in an NumPy array
arr2 = np.array([[1, 2, 3], ['a','b','c']])
print(arr2)
print(arr2.ndim)
print("-"*15)

# Create a three-dimensional array
arr3 = np.array([
    [[1, 2, 3], ['a','b','c']],
    [[1, 2, 3], ['a','b',' ']],
    [[1, 2, 3], ['a','b',' ']],
    [[1, 2, 3], ['a','b',' ']]
])
print(arr3)
print(arr3.ndim)
print("-"*15)

# Check the shape of the array
print(arr3.shape) # (layers, rows, columns)
print("-"*15)

[1 2 3 4]
<class 'numpy.ndarray'>
---------------
[2 4 6 8]
---------------
[['1' '2' '3']
 ['a' 'b' 'c']]
2
---------------
[[['1' '2' '3']
  ['a' 'b' 'c']]

 [['1' '2' '3']
  ['a' 'b' ' ']]

 [['1' '2' '3']
  ['a' 'b' ' ']]

 [['1' '2' '3']
  ['a' 'b' ' ']]]
3
---------------
(4, 2, 3)
---------------


In [5]:
# Chain indexing
print(arr3[0][0][0])

# Multi-dimensional indexing
print(arr3[1, 1, 1])
print("-"*15)

# Row Slicing (array[start:end:step])
arr4 = np.array([[1,2,3,4], 
                 [5,6,7,8], 
                 [9,10,11,12], 
                 [13,14,15,16]])
print(arr4[1:3])
print("-"*15)
print(arr4[::2])

1
b
---------------
[[ 5  6  7  8]
 [ 9 10 11 12]]
---------------
[[ 1  2  3  4]
 [ 9 10 11 12]]


In [6]:
# Column Slicing (array[start:end:step])
arr4 = np.array([[1,2,3,4], 
                 [5,6,7,8], 
                 [9,10,11,12], 
                 [13,14,15,16]])

print(arr4[:, 2]) # arr4[row, column])
print("-"*15)
print(arr4[:2, -2:]) # First two rows and last two columns
print("-"*15)
print(arr4[-2:, ::-1]) # Last two rows and reverse the order for each column

[ 3  7 11 15]
---------------
[[3 4]
 [7 8]]
---------------
[[12 11 10  9]
 [16 15 14 13]]


In [9]:
# Scalar arithmetic

array = np.array([1, 2, 3])
print(array + 1)
print(array - 2)
print(array * 3)
print(array / 4)
print(array ** 5)

[2 3 4]
[-1  0  1]
[3 6 9]
[0.25 0.5  0.75]
[  1  32 243]


In [14]:
# Vectorized math functions

array = np.array([1.01, 2.5, 3.99])
print(np.sqrt(array))
print(np.round(array))
print(np.floor(array))
print(np.ceil(array))
print(np.pi)
print("-"*15)
radii = np.array([1, 2, 3])
print(np.pi * radii ** 2)

[1.00498756 1.58113883 1.99749844]
[1. 2. 4.]
[1. 2. 3.]
[2. 3. 4.]
3.141592653589793
---------------
[ 3.14159265 12.56637061 28.27433388]


In [17]:
# Element-wise arithmetic

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)
print(array1 ** array2) 

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [21]:
# Comparison operators

scores = np.array([91, 55, 100, 73, 82, 64])
print(scores == 100)
print(scores >= 60)
print(scores < 60)

scores[scores < 60] = 0
print(scores)

[False False  True False False False]
[ True False  True  True  True  True]
[False  True False False False False]
[ 91   0 100  73  82  64]


In [23]:
# Broadcasting allows NumPy to perform operations on arrays
# with different shapes by virtually expanding dimensions
# so they match the larger array's shape.

# The dimensions have the same size.
# Or
# One of the dimensions has a size of 1.

array1 = np.array([[1, 2, 3, 4]])
array2 = np.array([[1], [2], [3], [4]])

print(array1.shape)
print(array2.shape)

print(array1 * array2)

(1, 4)
(4, 1)
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [31]:
# Aggregate functions = summarize data and typically return a single value

array = np.array([[1, 2, 3, 4, 5], 
                  [6, 7, 8, 9, 10]])
print(np.sum(array))
print(np.mean(array))
print(np.std(array))
print(np.var(array))
print(np.min(array))
print(np.max(array))
print(np.argmin(array)) # Position of the minimum value
print(np.argmax(array)) # Position of the greatest value

print(np.sum(array, axis=0)) # 0 sums all columns
print(np.sum(array, axis=1)) # 1 sums all rows

55
5.5
2.8722813232690143
8.25
1
10
0
9
[ 7  9 11 13 15]
[15 40]


In [40]:
# Filtering

ages = np.array([[21, 17, 19, 20, 16, 30, 18, 65], 
                 [39, 22, 15, 99, 18, 19, 20, 21]])

teenagers = ages[ages < 18]
print(teenagers)

adults = ages[(ages >= 18) & (ages < 65)]
print(adults)

seniors = ages[ages >= 65]
print(seniors)

evens = ages[ages % 2 == 0]
print(f"{evens}\n")

adults2 = np.where(ages >= 18, ages, 0) # Condition, Array, Fill value. This preserves the shape
print(adults2)

[17 16 15]
[21 19 20 30 18 39 22 18 19 20 21]
[65 99]
[20 16 30 18 22 18 20]

[[21  0 19 20  0 30 18 65]
 [39 22  0 99 18 19 20 21]]


In [60]:
# Random numbers

rng = np.random.default_rng(seed=1) # rng means Random Number Generator
print(rng.integers(low=1, high=101, size=(3,2))) # Integer

np.random.seed(1)
print(np.random.uniform(low=-1, high=1, size=(3,2,1))) # Float

array = np.array([1, 2, 3, 4, 5])
rng.shuffle(array) # Shuffling
print(array)
print(rng.choice(array, size=(1, 2))) # Random selection

[[48 52]
 [76 96]
 [ 4 15]]
[[[-0.16595599]
  [ 0.44064899]]

 [[-0.99977125]
  [-0.39533485]]

 [[-0.70648822]
  [-0.81532281]]]
[4 1 2 5 3]
[[3 2]]
